### ISSUE TITLE
Extraction of metrics in all tracts

### ISSUE THREAD

**Issue by Kaonashi22** [sct-pipeline/spine-park#10]
Can we add a loop to extract metrics (MT, T1, diffusion) in all regions and tracts in the "info_label.txt" file?

**Comment by jcohenadad** [comment]
Yes, we can certainly to that. I will implement it after we merge #8

**Comment by Kaonashi22** [comment]
Can we update the script to extract the metrics in all tracts ?

**Comment by jcohenadad** [comment]
sure-- i'll try my best to do it today

**Comment by jcohenadad** [comment]
how do you want the results? aggregated into a single CSV file, or one CSV file per tract?

**Comment by Kaonashi22** [comment]
Thank you!
A csv file per tract would be more convenient
________________________________

**Comment by jcohenadad** [comment]
Another consideration: some tracts are _veeeeeery_ small (ie: less than a mm2 per axial slice). When considering tracts in isolation, metrics will be more prone to noise, hence if there is a pathology-related effect, it would possibly be non-statistically significant. Whereas when aggregating across tracts, the sensitivity to detect changes statistically will be higher. So my recommendation would be to aggregate tracts instead of studying them in isolation. Aggregation should follow hypotheses in terms of the tracts that are expected to be affected (eg: all descending tracts?)

**Comment by Kaonashi22** [comment]
I'm particularly interested in the intermedio-lateral columns, located in the lateral horns (in green). I'll look at it more in detail. 
![image](https://github.com/sct-pipeline/spine-park/assets/155473122/8e6334d7-c2a5-49ff-860a-3d009ca9ef98)

**Comment by jcohenadad** [comment]
could you suggest which tracts to aggregate from the [`info_label.txt`](https://github.com/spinalcordtoolbox/PAM50/blob/master/atlas/info_label.txt)

**Comment by Kaonashi22** [comment]
The region that I'm interested (intermedio-lateral columns) should be located in these GM areas (~16 voxels in the axial plane for each side):
_32, GM left intermediate zone, PAM50_atlas_32.nii.gz
33, GM right intermediate zone, PAM50_atlas_33.nii.gz_
Do you think if it can be studied given the size?

WE can can also look at the GM globally
_52, gray matter, 30:35_

These could be "control regions":
_51, white matter, 0:29
53, dorsal columns, 0:3
54, lateral funiculi, 4:13
55, ventral funiculi, 14:29

30, GM left ventral horn, PAM50_atlas_30.nii.gz
31, GM right ventral horn, PAM50_atlas_31.nii.gz

34, GM left dorsal horn, PAM50_atlas_34.nii.gz
35, GM right dorsal horn, PAM50_atlas_35.nii.gz

If not too small
4, WM left lateral corticospinal tract, PAM50_atlas_04.nii.gz
5, WM right lateral corticospinal tract, PAM50_atlas_05.nii.gz_

**Comment by jcohenadad** [comment]
ok great, this is very helpful. Just to clarify, the regions you listed (eg: 32, 33): are you suggesting to merge them? (again, the pros in merging is the better robustness to noise)

**Comment by Kaonashi22** [comment]
I think we can merge right and left (eg: 32 and 33)

**Comment by jcohenadad** [comment]
Good, so I'll produce the following extraction strategies (one extraction per bullet point):
- 32,33
- 52
- 51
- 53:55
- 30,31
- 34,35
- 4,5

**Comment by Kaonashi22** [comment]
we can merge 54 and 55, but I would keep 53 separately unless you think it's too small
Sounds good for the rest

**Comment by Kaonashi22** [comment]
I'm also thinking it could be interesting to merge all ascending vs descending tracts

**Comment by jcohenadad** [comment]
> I'm also thinking it could be interesting to merge all ascending vs descending tracts

could you please list the numbers to be included for the ascending vs. descending? that would save me some time 😊

**Comment by Kaonashi22** [comment]
**descending**: 4 5 8 9 10 11 16 17 18 19 20 21 22 23 24 25 26 27

**ascending**: 0 1 2 3 6 7 12 13 14 15

**Comment by Kaonashi22** [comment]
Thanks Julien!

**Comment by jcohenadad** [comment]
Great, here is the updated list:

- 32,33
- 52
- 51
- 53
- 54:55
- 30,31
- 34,35
- 4,5
- 4,5,8,9,10,11,16,17,18,19,20,21,22,23,24,25,26,27
- 0,1,2,3,6,7,12,13,14,15

**Comment by Kaonashi22** [comment]
Thank you!

**Comment by jcohenadad** [comment]
@Kaonashi22 can you give it a try with https://github.com/sct-pipeline/spine-park/commit/9ad4422f84001a3f5d70c70b3939dea30538faa8 ?

**Comment by Kaonashi22** [comment]
Using the last version https://github.com/sct-pipeline/spine-park/commit/9ad4422f84001a3f5d70c70b3939dea30538faa8 ?, here is the output I got 
[DWI_FA.csv](https://github.com/sct-pipeline/spine-park/files/15194485/DWI_FA.csv)
[MTR_in_DC.csv](https://github.com/sct-pipeline/spine-park/files/15194486/MTR_in_DC.csv)

The columns voxels, map and std are empty... 
Also, the results corresponding to one subject are on "non-contiguous" rows

**Comment by jcohenadad** [comment]
https://github.com/sct-pipeline/spine-park/issues/10#issuecomment-2091831202 this error is caused by an issue which I've fixed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4469. Once it is merged, you can `git pull` from SCT's master version and from spine-park and the bug should go away.

**Comment by Kaonashi22** [comment]
After doing "git pull" and using the new script ([cb51fb6](https://github.com/sct-pipeline/spine-park/commit/cb51fb67b2763901ee3692cfe6dd792065850a0b)), I still have the same error

[err.batch_processing_sub-AM267.log](https://github.com/sct-pipeline/spine-park/files/15213413/err.batch_processing_sub-AM267.log)

**Comment by jcohenadad** [comment]
can you send me:
- mtr.nii.gz
- label_MT/atlas
- label_MT/template/PAM50_levels.nii.gz

**Comment by Kaonashi22** [comment]
[mtr.nii.gz](https://githu
[atlas.zip](https://github.com/sct-pipeline/spine-park/files/15213536/atlas.zip)
b.com/sct-pipeline/spine-par
[PAM50_levels.nii.gz](https://github.com/sct-pipeline/spine-park/files/15213537/PAM50_levels.nii.gz)
k/files/15213535/mtr.nii.gz)

**Comment by Kaonashi22** [comment]
Not sure whether you can open mtr.nii.gz and label_MT/atlas. I'm resending

[mtr.nii.gz](https://github.com/sct-pipeline/spine-park/files/15213544/mtr.nii.gz)

**Comment by Kaonashi22** [comment]
[atlas.zip](https://github.com/sct-pipeline/spine-park/files/15213554/atlas.zip)

**Comment by jcohenadad** [comment]
ah! i see, because https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4469 is not merged yet-- once it is merged you will be able to do it-- tagging @joshuacwnewton who can inform you once merged--

**Comment by Kaonashi22** [comment]
The first run gave me this error for a few subjects; when I rerun, it works

*** Generating Quality Control (QC) html report ***
Resample images to 0.600000x0.600000 vox
[33mConverting image from type 'uint8' to type 'float64' for linear interpolation[0m
Find the center of each slice
Traceback (most recent call last):
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 349, in <module>
    main(sys.argv[1:])
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 329, in main
    qc2.sct_deepseg(
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/reports/qc2.py", line 339, in sct_deepseg
    fig.savefig(img_path, format='png', transparent=True, dpi=300)
  The first run gave me this error:
  _File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/reports/qc2.py", line 90, in create_qc_entry
    with mutex(name="sct_qc"):
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/export02/data/lydiac/spinalcordtoolbox/spinalcordtoolbox/utils/fs.py", line 281, in mutex
    semaphore.acquire()
  File "/export02/data/lydiac/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/portalocker/utils.py", line 493, in acquire
    raise exceptions.AlreadyLocked()
portalocker.exceptions.AlreadyLocked_

**Comment by Kaonashi22** [comment]
These columns [vox] | MAP() | STD()  are still empty
[DWI_FA_30-31.csv](https://github.com/sct-pipeline/spine-park/files/15214081/DWI_FA_30-31.csv)

**Comment by joshuacwnewton** [comment]
Just to summarize the 2 different issues:

1. `MTR_in_DC.csv`:
   - `IndexError: index 52 is out of bounds`
   - Data was shared in [this comment](https://github.com/sct-pipeline/spine-park/issues/10#issuecomment-2094854994).
   - Issue was resolved by the SCT PR [#4469](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4469)
2. `DWI_FA_30-31.csv`
   - Empty cells in `[vox] | MAP() | STD()` columns.
   - Data has not been shared yet in this issue.
   I am a bit confused, as the columns appear to be non-empty in the CSV file you shaed:
   ![image](https://github.com/sct-pipeline/spine-park/assets/16181459/042e7ab3-a9fc-450f-b0e1-102546bef435)
   Could you clarify what the issue is?

(Other than that I will minimize some of the "Resolved" comments on this issue so that it is a little easier to navigate.)

**Comment by joshuacwnewton** [comment]
(I fixed the upload of the initial MTR data, then deleted the re-uploads.)

**Comment by Kaonashi22** [comment]
>        Could you clarify what the issue is?
These columns are empty when I open the csv files on the linux station where I'm running the analyses, but visible on my laptop, weird...
![image](https://github.com/sct-pipeline/spine-park/assets/155473122/d002b6d1-c768-4733-9632-b4a93076189b)

**Comment by Kaonashi22** [comment]
Right, the display is correct after changing the separator when opening the csv file, thank you!!

**Comment by joshuacwnewton** [comment]
Perfect! I think we can close this issue, then? (Since @jcohenadad previously closed this issue in https://github.com/sct-pipeline/spine-park/commit/9ad4422f84001a3f5d70c70b3939dea30538faa8.)

**Comment by Kaonashi22** [comment]
A few more questions/comments before you close the issue!
-is there a way to order the results by subject and level? I guess they are printed in the order in which they are generated. If not, I can do it manually
-on the screenshot attached, there are values corresponding to "slice 2" (C2 level) on the three dwi chunks; same for "slice 5"  (chunks 1 and 2) and "slice 9" (chunks 2 and 3).

![image](https://github.com/sct-pipeline/spine-park/assets/155473122/be411e91-3962-4a27-9f85-b72dcf972ea2)


-for some levels, values are equal to zero, but the maps look fine

**Comment by joshuacwnewton** [comment]
>  -is there a way to order the results by subject and level? I guess they are printed in the order in which they are generated. If not, I can do it manually

Yes, exactly. I imagine that this is because of parallel processing + using `-append`, so the rows are added as they're generated. I think manual ordering is the easiest solution to this.

>  -on the screenshot attached, there are values corresponding to "slice 2" (C2 level) on the three dwi chunks; same for "slice 5" (chunks 1 and 2) and "slice 9" (chunks 2 and 3).

Ahh, this is very strange. These seem like bugs to me? 

- for vertlevel 2, I wonder if this has to do with using the value `-vert 2:12` but the chunks only have a subsection of the range. (Maybe the code is automatically creating an entry for the first value (`2`) by default, even if vertlevel 2 is not in the image, which would definitely be a bug.)
- for vertlevel 5/9, it seems like those levels are at the interface between chunks 1/2 and chunks 2/3.

> -for some levels, values are equal to zero, but the maps look fine

This seems related to the problem above (vertlevels at the start and vertlevels at the interface between the chunks). I have a feeling if we solve the erroneous table entries, then the zero values will go away too.

**Comment by jcohenadad** [comment]
slice « 2 » is not located at the same physical location (ie absolute scanner coordinates) across chunks

**Comment by jcohenadad** [comment]
There are different ways to do that, depending on how you are going to use the information, some programatical ways are more optimal than others. To give you an example, here is a syntax:

```console
for chunk in 1 2 3 ; do sct_extract_metric -i sub-BB277_chunk-${chunk}_DWI_moco_FA.nii.gz -l 51 -f label_sub-BB277_chunk-${chunk}_DWI_moco/atlas/ -vert 1:12 -perlevel 1 -vertfile label_sub-BB277_chunk-${chunk}_DWI_moco/template/PAM50_levels.nii.gz -o levels.csv -append 1 ; done
```

That generates this output file: [levels.csv](https://github.com/sct-pipeline/spine-park/files/15257965/levels.csv), which lists what levels are present in a chunk, and what are the corresponding slices for each level.

**Comment by Kaonashi22** [comment]
I see on the csv file that some vertebral levels are still extracted from different chunks: for example level 10 from chunks 1 and 3; chunk 1 doesn't cover this level (upper part of the cord)

**Comment by jcohenadad** [comment]
> I see on the csv file that some vertebral levels are still extracted from different chunks: for example level 10 from chunks 1 and 3; chunk 1 doesn't cover this level (upper part of the cord)

can you please share the CSV file and the data so I can reproduce/understand

**Comment by Kaonashi22** [comment]
This is the csv file that you shared here:
> That generates this output file: [levels.csv](https://github.com/sct-pipeline/spine-park/files/15257965/levels.csv), which lists what levels are present in a chunk, and what are the corresponding slices for each level.

**Comment by jcohenadad** [comment]
If you overlay the chunks on the T2w image, you will notice that chunk 1 is not the top chunk but the middle one, which explains the overlap of vertebral levels in the CSV file:

![Screenshot 2024-05-15 at 5 21 47 PM](https://github.com/sct-pipeline/spine-park/assets/2482071/8e08976b-232f-45a8-967b-81b232b4a4df)

The reason is because I was working on a dataset that was created before I fixed https://github.com/sct-pipeline/spine-park/issues/16. If you run this in the latest version of the code if should work fine.

**Comment by Kaonashi22** [comment]
Got it, thank you!
Is there a way to add this command "do sct_extract_metric" to the script or I will have to run it at the end?

**Comment by jcohenadad** [comment]
> Is there a way to add this command "do sct_extract_metric" to the script or I will have to run it at the end?

Fixed in ad7a4ba1df751f2ee116efe17f2c3a11b7b70adf. I haven't checked the code so please run in one subject to make sure there is no bug

**Comment by Kaonashi22** [comment]
The code exited with this error: _FileNotFoundError: [Errno 2] No such file or directory: '/dagher/dagher11/lydia11/SPINE_park/Test_1505/data_processed/sub-AM267/dwi/sub-AM267_chunk-1_DWI_moco/template/PAM50_levels.nii.gz'_

I think the actual name of the folder it's looking for is _label_sub-AM267_chunk-1_DWI_moco_
Chunks 2 and 3 were not processed.

[err.batch_processing_sub-AM267.log](https://github.com/sct-pipeline/spine-park/files/15337248/err.batch_processing_sub-AM267.log)

**Comment by jcohenadad** [comment]
Sorry about that-- it is now fixed in ecd02d1. I tested the code and it runs on my end.

**Comment by Kaonashi22** [comment]
Thank you! I'm testing the new version

**Comment by Kaonashi22** [comment]
Using the last version of the script, I got these results. There is a level 2 for the three chunks, but only chunk 1 has values as expected (zero for chunks 2 and 3). Is there a reason?
For this specific subject, chunks 1 and partially 2 cover level 4, but together they fully cover it. Should I take the mean of the values in the two chunks?



![image](https://github.com/sct-pipeline/spine-park/assets/155473122/4001f2e0-6b3a-4f3b-b4e4-b00b43cd9d59)

**Comment by jcohenadad** [comment]
> Using the last version of the script, I got these results. There is a level 2 for the three chunks, but only chunk 1 has values as expected (zero for chunks 2 and 3). Is there a reason?

https://github.com/sct-pipeline/spine-park/issues/35

> For this specific subject, chunks 1 and partially 2 cover level 4, but together they fully cover it. Should I take the mean of the values in the two chunks?

Discussion opened here: https://github.com/sct-pipeline/spine-park/issues/14
